# Generated by Django 3.2.3 on 2022-05-16 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo31662', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo_postal', models.IntegerField(null=True)),
                ('provincia_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='envio.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='DatosEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('numero_de_seguimiento', models.CharField(max_length=200, null=True)),
                ('numero_de_retiro', models.CharField(max_length=200, null=True)),
                ('etiqueta_impresa', models.BooleanField(default=False, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200, null=True)),
                ('indicaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compra.compra')),
            ],
        ),
    ]
