# Generated by Django 3.2.3 on 2022-05-16 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False, null=True)),
                ('medio_de_pago', models.CharField(max_length=100, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PREPARANDO ORDEN', 'PREPARANDO ORDEN'), ('LISTA PARA RETIRAR', 'LISTA PARA RETIRAR'), ('EN CAMINO', 'EN CAMINO'), ('ENTREGADO', 'ENTREGADO')], max_length=200, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productoscalificacion')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compra.compra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Item Comprado',
                'verbose_name_plural': 'Items Comprados',
            },
        ),
    ]
