# Generated by Django 3.2.3 on 2022-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20220525_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='especial',
            field=models.BooleanField(default=None),
        ),
    ]
